### ISSUE TITLE
Bug: SSML with "lang" and "voice" not supported

### ISSUE THREAD

**Issue by fboerncke** [alexa-games/litexa#113]
# Bug Report
When using the command "say" ist seems that SSML Tags like &lt;lang&gt; and &lt;voice&gt; are not supported. 

## Litexa Version
0.3.1

## Current Behavior
From looking at the code it seems that the tags named above and others are filtered out intentionally. Or the other way round: tags not explicitely allowed are forbidden.

Is there a deeper reason for this? This seems like a restrictive limitation for a big amount of use cases I can think of.

## Expected Behavior
Simply forward ssml tags to response

## Steps to Reproduce
 
  say "<lang xml:lang=\"en-US\"><voice name="'+voice+'">This is a nice picture</voice></lang>."
 
  ==>

[lambda] +111ms lambda deployment failed
[deploy] +406ms main.litexa[39:9]: Error: unknown tag <lang>

**Comment by fboerncke** [comment]
Meanwhile I learned that the example given under

https://www.litexa.com/book/backdoor.html#_2-pending-response-data

with the method "addCustomSSML" offers a workaround which works for me. 

But I am still curious why some SSML options do work and some do not?

**Comment by ayrc** [comment]
Litexa's SSML *shorthand* syntax only supports a subset of the SSML tags. You are still able to use your own SSML tags, by escaping them:

```coffeescript
  say "\<amazon:effect name="whispered">Hi. I am not a human.\</amazon:effect>"
  say "\<break time='500ms'>"
```
Note that a `\` is necessary at the beginning of each tag.

Here is the documentation on the topic: https://www.litexa.com/book/presentation.html#escaping-control-characters

I guess it would be good if we included more examples.

**Comment by fboerncke** [comment]
Thanks, this case can therfore be closed.
