### ISSUE TITLE
Documentation Bug: $newProduct ISP callback

### ISSUE THREAD

**Issue by cheruvian** [alexa-games/litexa#159]
# Bug Report
$newProduct is undocumented in the ISP callback.

https://www.litexa.com/book/monetization.html#step-6-handle-purchase-result

I know there exists an `$newProduct.name` from the docs, but not sure exactly where that name comes from.  Through trial and error (and looking through the pulled monetization files) I also know that there is a `$newProduct.referenceName`

```
/**
* @param $newProduct.name - Name from ...?
* @param $newProduct.referenceName - Reference name specified in the ASK Console or your `isp/DEPLOYMENT/reference-name.json` file
**/

**Comment by joseifert** [comment]
Hi cheruvian. `$newProduct` is clearly documented in the TIP of the https://www.litexa.com/book/monetization.html#step-6-handle-purchase-result section.

If anything is unclear with that documentation, please elaborate. Otherwise, please close this issue.

**Comment by cheruvian** [comment]
Totally missed that section, not quite sure how. Perhaps moving it to before the example and using a standard notation for documentation may make it pop more (see: @jsdoc). 

Closing.
