### ISSUE TITLE
Feature: port to ASK CLI V2

### ISSUE THREAD

**Issue by fboerncke** [alexa-games/litexa#167]
# Feature Request

Is there any chance to see Litexa ported to ASK CLI V2?

**Comment by ayrc** [comment]
Hello Frank,

Thank you for asking. As of right now we don't have bandwidth to work on feature requests for Litexa, but we can prioritize this if we do. As Litexa is open source, you are also welcome to submit a pull request and we would be happy to review it.

**Comment by amzn-chris-subagio** [comment]
Hey Frank, happy to say it should be up and running with ask-cli V2 now!

**Comment by fboerncke** [comment]
This is so great! Thank you. 

This was the one reason I felt stuck on ask-cli V1. 
Now I can migrate my whole development environment to V2.
