### ISSUE TITLE
Feature: Offer a trigger to switch off "hidden" DynamoDb activity

### ISSUE THREAD

**Issue by fboerncke** [alexa-games/litexa#169]
# Feature Request

Hello Litexa Team,

not sure if this is a bug report or a feature request: over the last months I implemented quite a number of small skills using Litexa and currently I am in the process of building a bigger one which I hope will go live this month. Litexa is a great framework and I don't understand why it is not getting much more attention in the community.

What I noticed in the past is that since I am using Litexa my AWS traffic goes up quite a lot. In May it even went beyound the limit of 100$ and AWS tried to charge me money. After some discussion I got the money back but the message was kind of: "Don't do it again". But I don't feel guilty of doing anything wrong.

When looking at where the main traffic comes from I see that this is due to DynamoDb activity. Now the point is that I am not using persistence explicitely but Litexa is doing something behind the scene with DynamoDb even if you dont use persistent @variables in your code. 

**My question is if there is any way to switch off this behaviour? Something like a trigger which says: "Make the skill not use DynamoDb at all". This would not affect my skills functionality but definitely save me money in the future!**

I invest a lot of free time to build skills and make Alexa an even greater platform but it doesn't feel right if I have to pay money for this investment.

Best regards,
Frank

**Comment by ayrc** [comment]
Hi Frank,

This is something I personally get concerned about, too :). Upon each skill's creation, Litexa sets DynamoDB settings at 10 RCU/WCU. DynamoDB currently has a free tier limit of 25 RCU/RWU, without autoscaling enabled. Litexa will use DynamoDB each skill interaction for its internal workings; they're the `__variableName` fields within the Data attribute of your DynamoDB tables that keep track of things like Litexa state and monetization.

A few things you can try out in the meantime:

* For each skill, lower the capacity and disable autoscaling. This is not recommended on live skills.
* For each skill, change capacity to On-Demand pricing. This will incur a cost per DynamoDB transaction (every skill interaction), but might make the most sense given the traffic to each skill (not-live skill only invoked by you).

We're definitely considering an implementation option where Litexa doesn't use a DynamoDB table at all and uses the skill session attributes instead. Unfortunately like all other Litexa requests, we have minimal bandwidth to work on them now.

For the most up to date information:
* AWS free tier, visit https://aws.amazon.com/free/
* DynamoDB pricing: https://aws.amazon.com/dynamodb/pricing/

Thank you for your continued feedback and support on Litexa! We definitely appreciate it.

**Comment by fboerncke** [comment]
Thanks a lot for your answer though I am not happy to read this. Last month I received a bill from AWS because of this "feature" which I don't really use but cannot switch off. 

I will follow your recommendation about lowering the capacity understanding that this will not help in the long term perspective. Looking at my current project I might have to rethink my strategy about the way I make use of Litexa. 

At least I understand what has been going on last month, thanks again for offering this perspective. 

I know it takes time to write such an answer! Hopefully your team will get the resources to make Litexa an even better framework. During various Alexa Twitch sessions I will continue to spread the word regarding Litexa as I did already in the past ...

**Comment by ayrc** [comment]
Thank you again! If we get the time to work on features, we can prioritize this first.

**Comment by amzn-chris-subagio** [comment]
So, I had a little think on this, and at the top level redirecting the persistent store to sessionAttributes is actually really easy. The linked PR would introduce a new project level configuration that would control the switch. When you indicate `useSessionAttributesForPersistentStore` should be true, then @ variables would still live between interactions in a single session, but would disappear once the skill quit. Every launch would effectively be a database wipe.

Would this work for you @fboerncke ?

**Comment by fboerncke** [comment]
Hello Chris,

your approach sounds great and this would have helped me with the situation which I experienced in May when running out of free tier.



I want to add a thought though which occurs to me but I am not sure if this makes sense in the long term: Maybe there are use cases where it makes sense to have both variables db-persisted and others session-persisted within the same skill? Right now we have:

- $requestVariable
- @dbPersistedVariable

I remember that when I was new to Litexa and read the documentation that I have been looking for some notation for session variables. Perhaps it makes sense to add a new notation like:

- %sessionVariable or 
- &sessionVariable or
- #sessionVariable
- ...

This way you could make explicit within the literal code what the expected behaviour is. While generating and deploying the code  for AWS Litexa could then look up if there are any @-Variables around. If "yes", then a DynamoDb instance would be configured and if "no" the code would be deployed without DynamoDb.

Just a thought,

Frank

**Comment by amzn-chris-subagio** [comment]
Yeah, we've been thinking about that here too. We've always needed persistent variables because for all the kinds of skills we've written we've always supported resuming, which for various reasons necessarily means dumping state to persistent store at every turn, so we've never organically needed the session attributes. It's hard to reason about something clearly when aren't using it for yourself, so thank you for the fresh context!

I'd like to give it more thought for now, before adding new syntax. For one thing, once we split and support both, there's probably a much clearer reason to read/write lazily, i.e. only when an @ variable is encountered, which would be great, but right now the DB entry is also used as the concurrency guard, so we'd have to work out how we feel about that, and whether they should be decoupled by allowing an opt out of the guard even if you're using a persistent store, and how we should then think of the read/write guarantees for persistent variables.

In any case, I think this top level switch will cover the need for now, and I don't think it conflicts with a future where a session variable type exists, I reckon the switch would just make them function roughly equivalently.

One further question though: it occurred to me that perhaps we want this per-deployment rather than per-skill. I can see the case where a skill may be intended to be persistent, but may need test/temp deployments that don't care to persist, and would similarly benefit from skipping the database management. Would this be more useful, or just the same to you?

**Comment by fboerncke** [comment]
I understand that adding a new syntax goes much beyound adding a switch to deactivate DynamoDb. For sure it is a good idea to take some time to think about it. This was just a thought which I liked to share. 

Regarding adding the switch per skill or per deployment I thought about what I did last months with various skills and prototypes. There was not one use case where it would have been helpful to have this by deployment. I believe in cases I need DynamoDb in production I want to have it in test too. So I would argue it is fine to have this by skill.

**Comment by fboerncke** [comment]
Hello Chris,
as far as I can see this feature has been implemented but is not yet available in master / in the product? I would be happy to use it as this would make Litexa an even better framework :-)
Bye,
Frank

**Comment by amzn-chris-subagio** [comment]
Hey @fboerncke thanks for pinging! I've had it on my todo to push out a release for too long now. I've just update docs and such and pushed 0.7 out. That has the [new support for switching to session attributes instead](https://litexa.com/book/deployment.html#switching-the-persistent-store-to-session-attributes-instead). I hope that helps!

**Comment by fboerncke** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;}  This is so great, thank you. I'll give it a try next week. Bye,Frank                                                                                                                                             --Dr. Frank Börncke • Java Software, Beratung, Architektur, EntwicklungMargaretenstraße 6b • 82152 Krailling • frank.boerncke@gmail.comFon: +49(89)9760548-0 • Fax: +49(89)9760548-7 • www.boerncke.de                                                                                                                                                                           Von: notifications@github.comGesendet: 3. Oktober 2020 01:09An: litexa@noreply.github.comAntworten: reply@reply.github.comCc: frank@boerncke.de; mention@noreply.github.comBetreff: Re: [alexa-games/litexa] Feature: Offer a trigger to switch off "hidden" DynamoDb activity (#169)  
Hey @fboerncke thanks for pinging! I've had it on my todo to push out a release for too long now. I've just update docs and such and pushed 0.7 out. That has the new support for switching to session attributes instead. I hope that helps!
