### ISSUE TITLE
Built with Litexa: "Commander Speedo" is live (for your information)

### ISSUE THREAD

**Issue by fboerncke** [alexa-games/litexa#172]
Hello Litexa Team,

this is neither a bug report nor a feature request: as I have no idea how to contact you besides of this github environment I use this channel. 

Over the last months I implemented a number of small skills using Litexa but with today I published my so far most complex skill "Commander Speedo". You can see a short gameplay video on my YouTube channel: 

https://www.youtube.com/watch?v=sGgF0mxJ4Mo (sorry for bad image quality)

You will believe that there is a lot of dynamic APL going on in the background. Litexa helped me a lot to focus on the business logic while abstracting away the intent related stuff. Surprisingly the  main.litexa file is not that long.
 
If you have some free time available you might enjoy shooting some aliens & monsters via voice while collecting energy gems. When you do, please remember that part of the work is yours :-)
 
"Commander Speedo" would not exist without Litexa. Keep up the good work!

Regards,
Frank

**Comment by ayrc** [comment]
That's an impressive amount of APL manipulation and creative voice command system! Thank you as always for all your feedback :)

If you're interested in going further in experimenting with new screen-related technologies for Alexa, you can try out the [Web API](https://developer.amazon.com/en-US/blogs/alexa/alexa-skills-kit/2019/11/apply-for-the-alexa-web-api-for-games-developer-preview). There is also a learning curve, but works differently than APL and may provide you with more flexibility and control in your game.

**Comment by fboerncke** [comment]
Months ago I made a request to get access to the Web API. But I haven't  heard from them since then. 

In a reply on Twitter Mark Tucker wrote me that it took weeks for him to get a response. 

But I have so many ideas in my mind regarding Alexa that I don't feel blocked by this and therefore I focus on implementing other concepts.

**Comment by ayrc** [comment]
Awesome. I look forward to your future Alexa skills! :D
