### ISSUE TITLE
Bug: Broken link in documentation

### ISSUE THREAD

**Issue by ayrc** [alexa-games/litexa#65]
# Bug Report

## Litexa Version
0.3.0

## Current Behavior
Broken link (https://litexa.com/book/) on homepage in the section "Does Litexa handle Alexa feature X?"

## Expected Behavior
Should link to the book (clicking "the book" does an automatic redirect to "https://litexa.com/book/#foreword" but inputting the link directly creates a broken link).

## Steps to Reproduce
Click on link in that section

## Operating System
OSX 10.12.6, Firefox 69.0

**Comment by greghroberts** [comment]
This was fixed by updating our hosting configuration, no code changes needed.
