### ISSUE TITLE
Feature: AWS-deploy module: Update Lambda's default runtime to nodejs10.x

### ISSUE THREAD

**Issue by ayrc** [alexa-games/litexa#71]
# Feature Request
Make the Node.js default runtime `nodejs10.x` (in lambda.coffee) and also make this configurable (feature exists, but should verify).

## Current Litexa Version
0.3.1

## Current Behavior
Node.js runtime environment is `nodejs8.10`.

## Desired Behavior
Node.js default runtime environment is `nodejs10.x`, but make configurable.

## Additional Information
https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html

**Comment by hueezer** [comment]
It can be set in litexa.config.js like this:
```
{
  "deployments": {
    "development": {
      "module": "@litexa/deploy-aws",
      "S3BucketName": "suncoast-assets",
      "askProfile": "suncoast",
      "awsProfile": "prototyping",
      "lambdaConfiguration": {
        Runtime: "nodejs10.x"
      }
    }
  }
}
```

**Comment by lvalencia** [comment]
May I suggest this issue be renamed to "Update default Node JS Runtime" ? I think the core of this issue still stands, it looks like Lambda Node 8 Runtime is starting reach end of life (https://sinovi.uk/articles/node-js-8-end-of-life-december-31-2019) so it doesn't make sense for Litexa to default to nodejs8.10.

I would also suggest adding documentation to the lambda configuration override for `litexa.config.js` if it's not documented.

**Comment by ayrc** [comment]
Updated issue, and the lambda configuration override documentation is in a subsection in https://litexa.com/book/deployment.html#aws-configuration

**Comment by housed** [comment]
Closing this ticket.

Default Node runtime change: https://github.com/alexa-games/litexa/pull/121
Configurable Node runtime change to docs: https://github.com/alexa-games/litexa/pull/106
