### ISSUE TITLE
Litexa Syntax Highlighting Incompatible 

### ISSUE THREAD

**Issue by ahalp0217** [alexa-games/litexa#76]
# Issue Details
`Unable to install Extension 'litexa.litexa-syntax-highlighting-1.0.0' as it is not compatible with Code '1.27.2'.`

## Current Litexa Version
0.3.1

## Current Behavior
Can't install `litexa.litexa-syntax-highlighting-1.0.0.vsix` via 'install' button in the extensions marketplace or after manually downloading and installing the vsix file.

**Comment by greghroberts** [comment]
Hi @ahalp0217 , 

Confirming you are on VS Code 1.27 - https://code.visualstudio.com/updates/v1_27 ? That version appears to be a year old. 

Are you able to upgrade to latest?

**Comment by ahalp0217** [comment]
Ah, good catch. VS Code's "Check For Updates..." feature was saying everything was up to date. Manually installed the latest version and it works. Thanks!
